
package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import org.jamessipac.controlador.ControlDeRestaurante;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import org.jamessipac.controlador.ControlDeEmpleado;
import static org.jamessipac.vista.EleccionEmpleado.modelo2;

/**
 *En esta clase el cliente elige al restaurante en el que hará su pedido
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class EleccionRestaurante extends javax.swing.JFrame {
    public ControlDeRestaurante controlador=ControlDeRestaurante.getInstancia();

   public static DefaultTableModel modelo2;
    
    String id="";
    String calle="";
    String zona="";
    String lugar="";
    String telefono="";
    /**
     * Creates new form EleccionRestaurante
     */
    public EleccionRestaurante() {
        initComponents();
        
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);      
        

        
        modelo2=new DefaultTableModel();
        modelo2.addColumn("Id");
        modelo2.addColumn("Calle");
        modelo2.addColumn("Zona");
        modelo2.addColumn("Lugar");
        modelo2.addColumn("Teléfono");
        jTableRestaurante.setModel(modelo2);
        
        
        jTableRestaurante.addMouseListener(new MouseAdapter(){
        DefaultTableModel model=new DefaultTableModel();
        
        public void mouseClicked(MouseEvent e){
            int i=jTableRestaurante.getSelectedRow();
            id=(jTableRestaurante.getValueAt(i, 0)).toString();
            calle=(jTableRestaurante.getValueAt(i, 1)).toString();
            zona=(jTableRestaurante.getValueAt(i, 2)).toString();
            lugar=(jTableRestaurante.getValueAt(i, 3)).toString();
            telefono=(jTableRestaurante.getValueAt(i, 4)).toString();
        }
        });        
        this.setSize(860,460);
        this.setLocationRelativeTo(null);
    }

    /**
     * Con este metodo se muestran en la tabla los restaurantes contenidos en el ArrayList
     */
        public void mostrarRestaurantes(){
        String[][] vector=new String[controlador.cantidadRestaurantes()][5];
        for (int i = 0; i < controlador.cantidadRestaurantes(); i++) {
            vector[i][0]=controlador.listaDeRestaurantes.get(i).getId();
            vector[i][1]=controlador.listaDeRestaurantes.get(i).getCalle();
            vector[i][2]=controlador.listaDeRestaurantes.get(i).getZona();
            vector[i][3]=controlador.listaDeRestaurantes.get(i).getLugar();
            vector[i][4]=controlador.listaDeRestaurantes.get(i).getTelefono();
        }
        jTableRestaurante.setModel(new javax.swing.table.DefaultTableModel(vector, new String[]{"Id","Calle","Zona","Lugar","Teléfono"}));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnElegir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVerMenu = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRestaurante = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtZona = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtFase1Nombre = new javax.swing.JTextField();
        txtFase1Apellido = new javax.swing.JTextField();
        txtFase1Telefono = new javax.swing.JTextField();
        txtFase1Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegir);
        btnElegir.setBounds(451, 375, 72, 22);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(760, 330, 72, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Elija en cual de nuestros restaurantes hará su compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 460, 25);

        btnVerMenu.setText("Ver lista de restaurantes");
        btnVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerMenu);
        btnVerMenu.setBounds(16, 375, 260, 22);
        getContentPane().add(txtId);
        txtId.setBounds(680, 90, 154, 22);

        jTableRestaurante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Teléfono", "Dirección"
            }
        ));
        jScrollPane2.setViewportView(jTableRestaurante);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(16, 89, 507, 274);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Calle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 140, 33, 20);
        getContentPane().add(txtCalle);
        txtCalle.setBounds(680, 140, 154, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Zona");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 180, 34, 20);
        getContentPane().add(txtZona);
        txtZona.setBounds(680, 180, 154, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Lugar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 230, 38, 20);
        getContentPane().add(txtLugar);
        txtLugar.setBounds(680, 230, 154, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 270, 59, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(680, 270, 154, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 90, 13, 20);

        txtFase1Nombre.setText("Nombre Empleado");

        txtFase1Apellido.setText("Apellido Empleado");

        txtFase1Telefono.setText("Telefono Empleado");

        txtFase1Direccion.setText("Direccion Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtFase1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtFase1Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtFase1Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtFase1Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFase1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFase1Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFase1Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFase1Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 516, 894, 55);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 890, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Con este boton se elige al restaurante seleccionado
     * @param evt crea un evento al presionarlo
     */
    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
       txtId.setText(id);
       txtCalle.setText(calle);
       txtZona.setText(zona);
       txtLugar.setText(lugar);
       txtTelefono.setText(telefono);
    }//GEN-LAST:event_btnElegirActionPerformed
    /**
     * Con este boton se confirma la eleccion y se dirige a la ventana siguiente
     * @param evt crea un evento al presionarlo
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
     VistaCliente abrir=new VistaCliente();
     abrir.setVisible(true);
     this.setVisible(false);
   
     //PARA RESTAURANTE ELEGIDO   
     String id="Id: "+txtId.getText();
     VistaCliente.txtFase2Id.setText(id);
     String calle="Calle: "+txtCalle.getText();
     VistaCliente.txtFase2Calle.setText(calle);
     String zona="Zona: "+txtZona.getText();
     VistaCliente.txtFase2Zona.setText(zona);
     String lugar="Lugar: "+txtLugar.getText();
     VistaCliente.txtFase2Lugar.setText(lugar);
     String telefono="Teléfono: "+txtTelefono.getText();
     VistaCliente.txtFase2Telefono.setText(telefono);
     
     
     //PARA EMPLEADO ELEGIDO
     String nombreEmpleado="Nombre: "+txtFase1Nombre.getText();
     VistaCliente.txtFase2NombreE.setText(nombreEmpleado);
     String apellidoEmpleado="Apellido: "+txtFase1Apellido.getText();
     VistaCliente.txtFase2ApellidoE.setText(apellidoEmpleado);
     String telefonoEmpleado="Teléfono: "+txtFase1Telefono.getText();
     VistaCliente.txtFase2TelefonoE.setText(telefonoEmpleado);
     String direccionEmpleado="Dirección: "+txtFase1Direccion.getText();
     VistaCliente.txtFase2DireccionE.setText(direccionEmpleado);
    }//GEN-LAST:event_btnAceptarActionPerformed
    /**
     * Con este boton se muestran los datos en la tabla
     * @param evt 
     */
    private void btnVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMenuActionPerformed
        mostrarRestaurantes();      
    }//GEN-LAST:event_btnVerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnVerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRestaurante;
    private javax.swing.JTextField txtCalle;
    public static javax.swing.JTextField txtFase1Apellido;
    public static javax.swing.JTextField txtFase1Direccion;
    public static javax.swing.JTextField txtFase1Nombre;
    public static javax.swing.JTextField txtFase1Telefono;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
