package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *Esta clase representa la entrada del administrador al programa
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class LoginAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdministrador
     */
    public LoginAdministrador() {
        initComponents();
               
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);        
        
        this.setSize(500,340);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese la contraseña correcta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 380, 32);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(201, 192, 72, 22);
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(89, 126, 318, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 490, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Con este boton se verifica si la contraseña ingresada es la correcta o no
     * @param evt crea un evento al presionarlo
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int veces=0;        
        String contraseña="2022133";        
        String pass=new String(txtContraseña.getText());
        
        if(pass.equals(contraseña)){
            //System.out.println("Contraseña correcta");
            //System.out.println("Bienvenido!!!");
            MenuPrincipalAdministrador abrir=new MenuPrincipalAdministrador();
            abrir.setVisible(true);
            this.setVisible(false);
            veces=3;            

        }else{
            
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta!!!");
            txtContraseña.setText("");
            veces=veces+1;
            if(veces==3){
               JOptionPane.showMessageDialog(null,"Bloqueando sistema...");
            }
        }
          
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtContraseña;
    // End of variables declaration//GEN-END:variables
}
