package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *En esta clase se eligen las diferentes configuraciones y pasar al modo cliente
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class MenuPrincipalAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalAdministrador
     */
    public MenuPrincipalAdministrador() {
        initComponents();
        
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);
        
         this.setSize(500,340);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConfProductos = new javax.swing.JButton();
        btnConfRestaurantes = new javax.swing.JButton();
        btnConfEmpleados = new javax.swing.JButton();
        btnACliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido!!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 120, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Elija una opcion de configuración");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 400, 32);

        btnConfProductos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfProductos.setText("Configuración de productos");
        btnConfProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfProductos);
        btnConfProductos.setBounds(130, 120, 240, 28);

        btnConfRestaurantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfRestaurantes.setText("Configuración de restaurantes");
        btnConfRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfRestaurantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfRestaurantes);
        btnConfRestaurantes.setBounds(130, 160, 240, 28);

        btnConfEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfEmpleados.setText("Configuración de empleados");
        btnConfEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfEmpleados);
        btnConfEmpleados.setBounds(130, 210, 240, 28);

        btnACliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnACliente.setText("Cambiar a modo cliente");
        btnACliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnACliente);
        btnACliente.setBounds(130, 250, 240, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 490, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Con este boton se dirige a la configuracion de productos
     * @param evt crea un evento al presionarlo
     */
    private void btnConfProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfProductosActionPerformed
        VistaConfiguracionProductos abrir=new VistaConfiguracionProductos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConfProductosActionPerformed
    /**
     * Con este boton se dirige a la configuracion de restaurantes
     * @param evt crea un evento al presionarlo
     */
    private void btnConfRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfRestaurantesActionPerformed
        VistaConfiguracionRestaurantes abrir=new VistaConfiguracionRestaurantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConfRestaurantesActionPerformed
    /**
     * Con este boton se dirige a la configuracion de empleados
     * @param evt crea un evento al presionarlo
     */
    private void btnConfEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfEmpleadosActionPerformed
       VistaConfiguracionEmpleados abrir=new VistaConfiguracionEmpleados();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnConfEmpleadosActionPerformed
    /**
     * Con este boton se realiza el cambio de administrador a cliente
     * @param evt crea un evento al presionarlo
     */
    private void btnAClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAClienteActionPerformed
        EleccionEmpleado abrir=new EleccionEmpleado();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnACliente;
    private javax.swing.JButton btnConfEmpleados;
    private javax.swing.JButton btnConfProductos;
    private javax.swing.JButton btnConfRestaurantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
