
package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;
import org.jamessipac.modelo.Restaurante;
import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jamessipac.controlador.ControlDeRestaurante;
import org.jamessipac.vista.EleccionRestaurante;
/**
 *Esta clase representa a la clase en la que se realizan las 4 funciones del CRUD
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class VistaConfiguracionRestaurantes extends javax.swing.JFrame {
    public ControlDeRestaurante controlador=ControlDeRestaurante.getInstancia();
    
    private static EleccionRestaurante instanciaEleccionRestaurante=null;
    
    String id="";
    String calle="";
    String zona="";
    String lugar="";
    String telefono="";
    
    /**
     * Creates new form VistaConfiguracionRestaurantes
     */
    public VistaConfiguracionRestaurantes() {
        initComponents();
        
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);
        
        jTableRestaurante.addMouseListener(new MouseAdapter(){
        DefaultTableModel model=new DefaultTableModel();
        
        public void mouseClicked(MouseEvent e){
            int i=jTableRestaurante.getSelectedRow();
            id=(jTableRestaurante.getValueAt(i, 0)).toString();
            calle=(jTableRestaurante.getValueAt(i, 1)).toString();
            zona=(jTableRestaurante.getValueAt(i, 2)).toString();
            lugar=(jTableRestaurante.getValueAt(i, 3)).toString();
            telefono=(jTableRestaurante.getValueAt(i, 4)).toString();
        }
        });
        
         this.setSize(970,460);
        this.setLocationRelativeTo(null);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtZona = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRestaurante = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Agregar datos del restaurante");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 236, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 70, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Calle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(46, 120, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Zona");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 160, 80, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Lugar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 70, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(46, 240, 80, 16);
        getContentPane().add(txtId);
        txtId.setBounds(130, 72, 198, 30);
        getContentPane().add(txtCalle);
        txtCalle.setBounds(130, 112, 198, 30);
        getContentPane().add(txtZona);
        txtZona.setBounds(130, 152, 197, 30);
        getContentPane().add(txtLugar);
        txtLugar.setBounds(130, 192, 198, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(130, 232, 198, 30);

        jTableRestaurante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Calle", "Zona", "Lugar", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jTableRestaurante);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(382, 73, 557, 275);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Lista de restaurantes");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(607, 25, 161, 25);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(50, 300, 90, 20);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(150, 300, 90, 20);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(250, 300, 100, 20);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambios);
        btnGuardarCambios.setBounds(130, 340, 150, 20);

        btnRegresar.setText("Regresar al menú principal del administrador");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(30, 380, 350, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Agrega los datos de un restaurante, el cual se agregara en el ArrayList
     * @param evt crea un evento al presionarlo
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Restaurante restaurante=new Restaurante(txtId.getText(), txtCalle.getText(),txtZona.getText(), txtLugar.getText(), txtTelefono.getText());
        controlador.crearRestaurante(restaurante);
        
        mostrarRestaurantes();
        
        txtId.setText("");
        txtCalle.setText("");
        txtZona.setText("");
        txtLugar.setText("");
        txtTelefono.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     * Con este boton se elimina a un restaurante contenido en el ArrayList
     * @param evt crea un evento al presionarlo
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        for (int i = 0; i <controlador.cantidadRestaurantes(); i++) {
            if(id.equals(controlador.listaDeRestaurantes.get(i).getId())){
                controlador.listaDeRestaurantes.remove(i);
            }
            mostrarRestaurantes();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Con este boton se muestran los datos de la fila que se haya seleccionado de la tabla
     * @param evt crea un evento al presionarlo
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       txtId.setText(id);
       txtCalle.setText(calle);
       txtZona.setText(zona);
       txtLugar.setText(lugar);
       txtTelefono.setText(telefono);
    }//GEN-LAST:event_btnActualizarActionPerformed
    /**
     * Este boton guarda las modificaciones que se realizaron al actualizar un restaurante
     * @param evt crea un evento al presionarlo
     */
    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        for (int i = 0; i < controlador.cantidadRestaurantes(); i++) {
            if(id.equals(controlador.listaDeRestaurantes.get(i).getId())){
            controlador.listaDeRestaurantes.get(i).setId(txtId.getText());
            controlador.listaDeRestaurantes.get(i).setCalle(txtCalle.getText());
            controlador.listaDeRestaurantes.get(i).setZona(txtZona.getText());
            controlador.listaDeRestaurantes.get(i).setLugar(txtLugar.getText());
            controlador.listaDeRestaurantes.get(i).setTelefono(txtTelefono.getText()); 
            }
        }
       txtId.setText(id);
       txtCalle.setText(calle);
       txtZona.setText(zona);
       txtLugar.setText(lugar);
       txtTelefono.setText(telefono);
       
       mostrarRestaurantes();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed
    /**
     * Con este boton se regresa al menu principal del administrador
     * @param evt crea un evento al presionarlo
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipalAdministrador abrir=new MenuPrincipalAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed
    /**
     * Con este metodo se muestran los datos en la tabla
     */
    public void mostrarRestaurantes(){
        String[][] vector=new String[controlador.cantidadRestaurantes()][5];
        for (int i = 0; i < controlador.cantidadRestaurantes(); i++) {
            vector[i][0]=controlador.listaDeRestaurantes.get(i).getId();
            vector[i][1]=controlador.listaDeRestaurantes.get(i).getCalle();
            vector[i][2]=controlador.listaDeRestaurantes.get(i).getZona();
            vector[i][3]=controlador.listaDeRestaurantes.get(i).getLugar();
            vector[i][4]=controlador.listaDeRestaurantes.get(i).getTelefono();
        }
        jTableRestaurante.setModel(new javax.swing.table.DefaultTableModel(vector, new String[]{"Id","Calle","Zona","Lugar","Teléfono"}));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConfiguracionRestaurantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRestaurante;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
