package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;
import org.jamessipac.modelo.Cliente;
import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
/**
 *En esta clase el usuario ingresa sus datos
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class VistaCliente extends javax.swing.JFrame {
    String nombre="";
    String apellido="";
    String direccion="";
    String telefono="";
    
    ArrayList<Cliente> listaDeClientes=new ArrayList<Cliente>(); 
    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
        
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);
        
        this.setSize(430,340);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFase2Id = new javax.swing.JTextField();
        txtFase2Calle = new javax.swing.JTextField();
        txtFase2Zona = new javax.swing.JTextField();
        txtFase2Lugar = new javax.swing.JTextField();
        txtFase2Telefono = new javax.swing.JTextField();
        txtFase2NombreE = new javax.swing.JTextField();
        txtFase2ApellidoE = new javax.swing.JTextField();
        txtFase2TelefonoE = new javax.swing.JTextField();
        txtFase2DireccionE = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese sus datos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 160, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 46, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 130, 45, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 170, 53, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 210, 50, 16);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(160, 80, 185, 30);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(160, 120, 185, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(160, 162, 185, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(160, 202, 185, 30);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(330, 260, 72, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 420, 310);

        txtFase2Id.setText("Id Restaurante");
        getContentPane().add(txtFase2Id);
        txtFase2Id.setBounds(20, 350, 90, 22);

        txtFase2Calle.setText("Calle Restaurante");
        getContentPane().add(txtFase2Calle);
        txtFase2Calle.setBounds(20, 390, 110, 22);

        txtFase2Zona.setText("Zona Restaurante");
        getContentPane().add(txtFase2Zona);
        txtFase2Zona.setBounds(20, 430, 110, 22);

        txtFase2Lugar.setText("Lugar Restaurante");
        getContentPane().add(txtFase2Lugar);
        txtFase2Lugar.setBounds(20, 470, 110, 22);

        txtFase2Telefono.setText("Telefono Restaurante");
        getContentPane().add(txtFase2Telefono);
        txtFase2Telefono.setBounds(20, 510, 110, 22);

        txtFase2NombreE.setText("Nombre Empleado");
        getContentPane().add(txtFase2NombreE);
        txtFase2NombreE.setBounds(320, 350, 140, 22);

        txtFase2ApellidoE.setText("Apellido Empleado");
        getContentPane().add(txtFase2ApellidoE);
        txtFase2ApellidoE.setBounds(320, 390, 130, 22);

        txtFase2TelefonoE.setText("Telefono Empleado");
        getContentPane().add(txtFase2TelefonoE);
        txtFase2TelefonoE.setBounds(320, 430, 130, 22);

        txtFase2DireccionE.setText("Direccion Empleado");
        getContentPane().add(txtFase2DireccionE);
        txtFase2DireccionE.setBounds(320, 480, 130, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Con este boton se dirige a la ventana de compra
     * @param evt crea un evento al presionarlo
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Cliente cliente=new Cliente(txtNombre.getText(),txtApellido.getText(),txtDireccion.getText(),txtTelefono.getText());
        listaDeClientes.add(cliente);
        VistaClienteCompra enviarDatos=new VistaClienteCompra();
        
        
        VistaClienteCompra abrir=new VistaClienteCompra();
        abrir.setVisible(true);
        this.setVisible(false);
        
        String nombre="Nombre: "+txtNombre.getText();
        VistaClienteCompra.lblNombreCliente.setText(nombre);
        String apellido="Apellido: "+txtApellido.getText();
        VistaClienteCompra.lblApellidoCliente.setText(apellido);
        String direccion="Dirección: "+txtDireccion.getText();
        VistaClienteCompra.lblDireccionCliente.setText(direccion);
        String telefono="Teléfono: "+txtTelefono.getText();
        VistaClienteCompra.lblTelefonoCliente.setText(telefono);
        
        
        //PARA DATOS DE RESTAURANTE ELEGIDO
        String calleRestaurante=txtFase2Calle.getText();
        VistaClienteCompra.lblFase3Calle.setText(calleRestaurante);
        String zonaRestaurante=txtFase2Zona.getText();
        VistaClienteCompra.lblFase3Zona.setText(zonaRestaurante);
        String lugarRestaurante=txtFase2Lugar.getText();
        VistaClienteCompra.lblFase3Lugar.setText(lugarRestaurante);
        String telefonoRestaurante=txtFase2Telefono.getText();
        VistaClienteCompra.lblFase3Telefono.setText(telefonoRestaurante);
        
        
        //PARA DATOS DE EMPLEADO ELEGIDO
        String nombreEmpleado=txtFase2NombreE.getText();
        VistaClienteCompra.lblFase3NombreE.setText(nombreEmpleado);
        String apellidoEmpleado=txtFase2ApellidoE.getText();
        VistaClienteCompra.lblFase3ApellidoE.setText(apellidoEmpleado);
        String telefonoEmpleado=txtFase2TelefonoE.getText();
        VistaClienteCompra.lblFase3TelefonoE.setText(telefonoEmpleado);
        String direccionEmpleado=txtFase2DireccionE.getText();
        VistaClienteCompra.lblFase3DireccionE.setText(direccionEmpleado);
     
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtFase2ApellidoE;
    public static javax.swing.JTextField txtFase2Calle;
    public static javax.swing.JTextField txtFase2DireccionE;
    public static javax.swing.JTextField txtFase2Id;
    public static javax.swing.JTextField txtFase2Lugar;
    public static javax.swing.JTextField txtFase2NombreE;
    public static javax.swing.JTextField txtFase2Telefono;
    public static javax.swing.JTextField txtFase2TelefonoE;
    public static javax.swing.JTextField txtFase2Zona;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
