package org.jamessipac.vista;
import java.awt.Image;
import java.awt.Toolkit;
import org.jamessipac.modelo.Empleado;
import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jamessipac.controlador.ControlDeEmpleado;
import org.jamessipac.vista.EleccionEmpleado;
/**
 *Esta clase representa a la clase en la que se realizan las 4 funciones del ArrayList
 * @author James Sipac
 * @since 18 de julio de 2022
 */
public class VistaConfiguracionEmpleados extends javax.swing.JFrame {
    public ControlDeEmpleado controlador=ControlDeEmpleado.getInstancia();
  
    String id="";
    String nombre="";
    String apellido="";
    String telefono="";
    String direccion="";
    
    //ArrayList<Empleado> listaDeEmpleados=new ArrayList<Empleado>();
    /**
     * Creates new form VistaConfiguracionEmpleados
     */
    public VistaConfiguracionEmpleados() {
        initComponents();
        
        this.setTitle("Pollo Campero");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/campero.png"));
        this.setIconImage(icono); 
        this.setLocationRelativeTo(null);
        
        jTableEmpleado.addMouseListener(new MouseAdapter(){
        DefaultTableModel model=new DefaultTableModel();
        
        public void mouseClicked(MouseEvent e){
            int i=jTableEmpleado.getSelectedRow();
            id=(jTableEmpleado.getValueAt(i, 0)).toString();
            nombre=(jTableEmpleado.getValueAt(i, 1)).toString();
            apellido=(jTableEmpleado.getValueAt(i, 2)).toString();
            telefono=(jTableEmpleado.getValueAt(i, 3)).toString();
            direccion=(jTableEmpleado.getValueAt(i, 4)).toString();
        }
        });
        
         this.setSize(970,450);
        this.setLocationRelativeTo(null);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Agregar datos del empleado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 228, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 70, 90, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 120, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 80, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 200, 90, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 250, 90, 16);
        getContentPane().add(txtId);
        txtId.setBounds(180, 70, 185, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(180, 110, 185, 30);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(180, 152, 185, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(180, 200, 185, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(180, 242, 185, 30);

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Teléfono", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 70, 507, 274);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Lista de empleados");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 30, 153, 25);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(62, 290, 90, 22);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(160, 290, 90, 22);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(260, 290, 100, 22);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambios);
        btnGuardarCambios.setBounds(130, 330, 160, 22);

        btnRegresar.setText("Regresar al menú principal del administrador");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(70, 360, 290, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1000pxl.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Agrega los datos de un empleado, el cual se agregara en el ArrayList
     * @param evt crea un evento al presionarlo
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Empleado empleado=new Empleado(txtId.getText(), txtNombre.getText(), txtApellido.getText(), txtTelefono.getText(), txtDireccion.getText());
        controlador.crearEmpleado(empleado);
        
        mostrarEmpleados();        

        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     * Con este boton se elimina a un empleado contenido en el ArrayList
     * @param evt crea un evento al presionarlo 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        for (int i = 0; i < controlador.cantidadEmpleados(); i++) {
            if(id.equals(controlador.listaDeEmpleados.get(i).getId())){
                controlador.listaDeEmpleados.remove(i);
            }
            mostrarEmpleados();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Con este boton se muestran los datos de la fina que se haya seleccionado en la tabla
     * @param evt crea un evento al presionarlo 
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       txtId.setText(id);
       txtNombre.setText(nombre);
       txtApellido.setText(apellido);
       txtTelefono.setText(telefono);
       txtDireccion.setText(direccion);
    }//GEN-LAST:event_btnActualizarActionPerformed
    /**
     * Este boton guarda las modificaciones que se realizaron al actualizar un empleado
     * @param evt crea un evento al precionarlo 
     */
    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        for (int i = 0; i < controlador.cantidadEmpleados(); i++) {
            if(id.equals(controlador.listaDeEmpleados.get(i).getId())){
                controlador.listaDeEmpleados.get(i).setId(txtId.getText());
                controlador.listaDeEmpleados.get(i).setNombre(txtNombre.getText());
                controlador.listaDeEmpleados.get(i).setApellido(txtApellido.getText());
                controlador.listaDeEmpleados.get(i).setTelefono(txtTelefono.getText());
                controlador.listaDeEmpleados.get(i).setDireccion(txtDireccion.getText());
            }
        }
       txtId.setText("");
       txtNombre.setText("");
       txtApellido.setText("");
       txtTelefono.setText("");
       txtDireccion.setText("");
       
       mostrarEmpleados();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed
    /**
     * Con este boton se regresa al menu principal del administrador
     * @param evt crea un evento al presionarlo
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipalAdministrador abrir=new MenuPrincipalAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed
    /**
     * Con este metodo se muestran lso datos en la tabla
     */
    public void mostrarEmpleados(){
        String[][] vector=new String[controlador.cantidadEmpleados()][5];
        for (int i = 0; i < controlador.cantidadEmpleados(); i++) {
            vector[i][0]=controlador.listaDeEmpleados.get(i).getId();
            vector[i][1]=controlador.listaDeEmpleados.get(i).getNombre();
            vector[i][2]=controlador.listaDeEmpleados.get(i).getApellido();
            vector[i][3]=controlador.listaDeEmpleados.get(i).getTelefono();
            vector[i][4]=controlador.listaDeEmpleados.get(i).getDireccion();
        }
        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(vector, new String[]{"Id","Nombre","Apellido","Teléfono","Dirección"}));
        
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConfiguracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConfiguracionEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
